### ISSUE TITLE
Issues w/ known bug workarounds

### ISSUE THREAD

**Issue by SeeingBlue** [spatialos/gdk-for-unity-fps-starter-project#64]
We are accepting issues and we want your [feedback](https://github.com/spatialos/gdk-for-unity#give-us-feedback).

-------

#### Description
When attempting to open FPS-SimulatedPlayerCoordinator it will not open. The open option is grey. So I cannot rebake the navmesh.

## Expected behaviour

I expected the ability to open the FPS-SimulatedPlayerCoordinator in the Hierarchy.

## Current behaviour

Hierarchy only contains an Untitled Scene. Dragging and Dropping, Double-Clicking, or Right-Click > Open does nothing for FPS-SimulatedPlayerCoordinator. It does not move to the Hierarchy.
Also Right-clicking Source_Shaders and selecting Reimport does appear to process but nothing happens. No icons change, and warnings go away. It doesn't appear to be having any effect.

## Possible solution

Unknown

## Steps to reproduce

1. I am not sure how you can reproduce this other than follow the steps in the getting started guide. 
2. This actually worked a couple days ago, but I wanted to start over so I deleted and recloning the repositories again so maybe something happened in the last couple of days?
3.
4.

## Environment

Setup the Unity FPS Starter

`C:\Users\SeeingBlue>spatial diagnose
Running basic diagnostics suite

Network Access Checks
Google Storage APIs Reachable: PASSED
Spatial Website Reachable: PASSED
Spatial Auth Server Reachable: PASSED
Spatial Maven Reachable: PASSED
Spatial API Reachable: PASSED
Spatial Secure Customer Proxy Reachable: PASSED
Can Bind to Local Port: PASSED
Spatial Proxy Reachable: PASSED
Spatial Website TLS and GRPCTLS Ports Reachable: PASSED
Spatial Auth TLS and GRPCTLS Ports Reachable: PASSED
Spatial Maven TLS and GRPCTLS Ports Reachable: PASSED
Spatial API TLS and GRPCTLS Ports Reachable: PASSED
Spatial Deployments Reachable: PASSED
Spatial Logs Reachable: PASSED
Spatial Monitoring Proxy Reachable: PASSED
Spatial Locator Reachable: PASSED
Maven Central Repo Reachable: PASSED
Sonatype OSS Repo Reachable: PASSED

All checks successful`

OS: 'Windows 10  (10.0.0) 64bit' Language: 'en' Physical Memory: 16229 MB
I updated both SpatialOS and Unity today. I was having the same issue with the previous versions too.
Previous Unity Version: 2018.2.14
Current Unity Version: 2018.2.16

I attached the editor.log too
[Editor.log](https://github.com/spatialos/gdk-for-unity-fps-starter-project/files/2585741/Editor.log)

**Comment by oblm** [comment]
Hey @SeeingBlue, thanks for reporting this. To clarify my understanding of the issue, you're trying to execute [these steps](https://docs.improbable.io/unity/alpha/content/get-started/open-project#bake-navmesh) in order to rebake the navmesh, but you can't open the `FPS-SimulatedPlayerCoordinator.unity`, so its contents (`ObjectPooling`, `GameSettings`, `SimulatedPlayerCoordinatorWorker` & `FPS-Start_Large`) aren't visible in the Hierarchy window?

I can't reproduce this issue, and but my impression is that this was caused by missing a setup when deleting and recloning the repositories.
The cleanest way to fix this would be to delete everything and run the [setup guide](https://docs.improbable.io/unity/alpha/content/get-started/set-up#set-up-your-machine) again.

If the problem persists, please try the following:

1. Please uninstall `2018.2.16` and reinstall `2018.2.14`, as this is the only Unity version currently supported by the GDK.
1.  Please confirm that when you run `git status` in your `gdk-for-unity` repo it reports `HEAD detached at 0.1.2`, which is the git tag of our latest release.

I hope this helps.
